### ISSUE TITLE
Delete Past Due Requests in Zambia

### ISSUE THREAD

**Issue by choquette33** [PeaceCorps/medlink#402]
All past due requests in Zambia are no longer relevant, and need to be deleted. I want to do this without sending a message to the PCVs to avoid confusion.

**Comment by jamesdabbs** [comment]
Done. Should they be necessary, the old orders are captured as part of Heroku backup #b019.

**Comment by choquette33** [comment]
The items are gone, but the blank orders are still showing up in the dashboard. I want to archive them, but I don't know what will happen if I send a response. (Just trying to avoid them getting a message about the order)

![image](https://cloud.githubusercontent.com/assets/2973990/8832595/fc28b41a-3077-11e5-99aa-075c3d8def5e.png)

**Comment by jamesdabbs** [comment]
Yup. That's pulling from a cached `waiting` value that has now been updated.

**Comment by choquette33** [comment]
Thanks James!
On Jul 22, 2015 1:33 PM, James Dabbs <notifications@github.com> wrote:Done. Should they be necessary, the old orders are captured as part of Heroku backup #b019.
